"""Recharts components."""
from __future__ import annotations

from reflex.utils import lazy_loader

_SUBMOD_ATTRS = {
    "cartesian": [
        "area",
        "bar",
        "line",
        "scatter",
        "x_axis",
        "y_axis",
        "z_axis",
        "brush",
        "cartesian_axis",
        "cartesian_grid",
        "reference_line",
        "reference_dot",
        "reference_area",
        "error_bar",
        "funnel",
    ],
    "charts": [
        "area_chart",
        "bar_chart",
        "line_chart",
        "composed_chart",
        "pie_chart",
        "radar_chart",
        "radial_bar_chart",
        "scatter_chart",
        "funnel_chart",
        "treemap",
    ],
    "general": [
        "responsive_container",
        "legend",
        "graphing_tooltip",
        "label",
        "label_list",
    ],
    "polar": [
        "pie",
        "radar",
        "radial_bar",
        "polar_angle_axis",
        "polar_grid",
        "polar_radius_axis",
    ],
    "recharts": [
        "LiteralAnimationEasing",
        "LiteralAreaType",
        "LiteralAxisType",
        "LiteralBarChartStackOffset",
        "LiteralComposedChartBaseValue",
        "LiteralDirection",
        "LiteralGridType",
        "LiteralIconType",
        "LiteralIfOverflow",
        "LiteralInterval",
        "LiteralLayout",
        "LiteralLegendAlign",
        "LiteralLegendType",
        "LiteralLineType",
        "LiteralOrientation",
        "LiteralOrientationLeftRightMiddle",
        "LiteralOrientationTopBottom",
        "LiteralOrientationTopBottomLeftRight",
        "LiteralPolarRadiusType",
        "LiteralScale",
        "LiteralShape",
        "LiteralStackOffset",
        "LiteralSyncMethod",
        "LiteralVerticalAlign",
    ],
}

__getattr__, __dir__, __all__ = lazy_loader.attach(
    __name__,
    submod_attrs=_SUBMOD_ATTRS,
)
