name: Deploy-Reflex-Apps-using-Hosting-CLI
description: 'Deploy Reflex apps using Hosting CLI'

inputs:
  reflex-app-repo:
    description: 'repository of the target app to deploy'
    required: true
  reflex-app-ref:
    description: 'reflex app ref to deploy. e.g. git sha or `main`'
    required: true
    default: 'main'
  reflex-pin:
    description: 'Reflex pin (@, ==, all ok)'
  cp-web-url:
    description: 'Control Plane web URL'
  cp-backend-url:
    description: 'Control Plane backend URL'
  cp-env:
    description: 'Control Plane environment: dev/staging/prod'
  deployment-key:
    description: 'Instance key used for deploy'
    required: true
  user-email:
    description: 'Email of the hosting service user deploying the app'
    required: true
  user-password:
    description: 'Password of the hosting service user deploying the app'
    required: true
  openai-api-key:
    description: 'If included, the openai api key will be used'
  with-local-db:
    description: 'Whether to upload the local db'
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Checkout the target app repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.reflex-app-repo }}
        path: reflex-app
        ref: ${{ inputs.reflex-app-ref }}
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Install requirements
      shell: bash
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --no-color --no-cache-dir -q .
        if [ -n "${{ inputs.reflex-pin }}" ]; then
          # override reflex pin
          sed -i '/^reflex[>=]/d' reflex-app/requirements.txt
          echo "" >> reflex-app/requirements.txt
          echo "reflex${{ inputs.reflex-pin }}" >> reflex-app/requirements.txt
        fi
        # Note, below sed command only works on ubuntu, not MacOS
        pip install "reflex${{ inputs.reflex-pin }}" --no-color --no-cache-dir -q -r reflex-app/requirements.txt
    - name: Deploy bot log in to hosting service
      shell: bash
      env:
        REFLEX_CLOUD_URL: ${{ inputs.cp-web-url }}
        REFLEX_CLOUD_BACKEND_URL: ${{ inputs.cp-backend-url }}
      run: |
        source venv/bin/activate
        access_token=$(curl "${REFLEX_CLOUD_BACKEND_URL}/authenticate/password" -u "${{ inputs.user-email }}:${{ inputs.user-password }}" -X POST)
        if [ -z "$access_token" ]; then
          echo "::error::Test user unable to log in" && exit 1
        fi
        mkdir -p ~/.local/share/reflex/
        # Bypass the login process by manually stashing a token in the hosting config file.
        echo "{\"access_token\": $access_token}" > ~/.local/share/reflex/hosting_v0.json
        reflex login
    - name: Deploy reflex-app using CLI
      env:
        REFLEX_CLOUD_URL: ${{ inputs.cp-web-url }}
        REFLEX_CLOUD_BACKEND_URL: ${{ inputs.cp-backend-url }}
      shell: bash
      run: |
        source venv/bin/activate
        cd reflex-app/
        export TELEMETRY_ENABLED=false
        reflex init
        if [ -n "${{ inputs.openai-api-key }}" ]; then
          export OPENAI_API_KEY=${{ inputs.openai-api-key }}
          add_env_flags="--env OPENAI_API_KEY=${{ inputs.openai-api-key }}"
        fi
        if [ "${{ inputs.with-local-db }}" == 'true' ]; then
          add_db_flags="--upload-db-file"
          # Here we also need to do migration on the local sqlite db
          reflex db init
          reflex db migrate
        fi
        reflex deploy --no-interactive -k ${{ inputs.deployment-key }} -r sjc ${add_env_flags} ${add_db_flags}
        listed="$(reflex deployments list | grep ${{ inputs.deployment-key }})"
        if [[ -z "$listed" ]]; then
          echo "::error::deploy was not successful" && exit 1
        fi
    - name: Check deployed reflex app is responsive
      env:
        REFLEX_CLOUD_URL: ${{ inputs.cp-web-url }}
        REFLEX_CLOUD_BACKEND_URL: ${{ inputs.cp-backend-url }}
        CP_ENV: ${{ inputs.cp-env }}
      shell: bash
      run: |
        source venv/bin/activate
        python ./scripts/check_site_responsive.py --env ${CP_ENV} --deployment-key ${{ inputs.deployment-key }} --frontend-retries 30 --backend-retries 90
