fail_fast: true
repos:
- repo: local
  hooks:
  - id: ruff-format
    name: ruff-format
    entry: ruff format
    language: system
    types_or: [python, markdown]
    require_serial: true
  - id: ruff-check
    name: ruff-check
    entry: ruff check
    language: system
    args: [--fix, --exit-non-zero-on-fix]
    types_or: [python, pyi]
    require_serial: true
- repo: local
  hooks:
  - id: codespell
    name: codespell
    entry: codespell
    language: system
    types: [text]
    require_serial: true
- repo: local
  hooks:
  - id: update-pyi-files
    name: update-pyi-files
    description: Update pyi files as needed
    entry: python3 scripts/make_pyi.py
    language: system
    always_run: true
    require_serial: true
- repo: local
  hooks:
  - id: pyright
    name: pyright
    entry: pyright
    language: system
    types: [python]
    require_serial: true
- repo: https://github.com/biomejs/pre-commit
  rev: 19865851e014cbe6138e295365f95ca51bf953f8 # v0.6.1
  hooks:
  - id: biome-format
    additional_dependencies: ['@biomejs/biome@2.4.8']
    args: [--indent-width, '2', --indent-style, space]
    exclude: (\.css$|docs/app/)
    require_serial: true
