"""Stub file for slider.py"""
# ------------------- DO NOT EDIT ----------------------
# This file was generated by `scripts/pyi_generator.py`!
# ------------------------------------------------------

from typing import Dict, Union, overload, Optional
from reflex.components.libs.chakra import ChakraComponent
from reflex.components.component import Component
from reflex.vars import Var, BaseVar, ComputedVar
from reflex.event import EventChain

class Slider(ChakraComponent):
    @overload
    @classmethod
    def create(cls, *children, value: Optional[Union[Var[int], int]] = None, color_scheme: Optional[Union[Var[str], str]] = None, default_value: Optional[Union[Var[int], int]] = None, direction: Optional[Union[Var[str], str]] = None, focus_thumb_on_change: Optional[Union[Var[bool], bool]] = None, is_disabled: Optional[Union[Var[bool], bool]] = None, is_read_only: Optional[Union[Var[bool], bool]] = None, is_reversed: Optional[Union[Var[bool], bool]] = None, min_: Optional[Union[Var[int], int]] = None, max_: Optional[Union[Var[int], int]] = None, step: Optional[Union[Var[int], int]] = None, min_steps_between_thumbs: Optional[Union[Var[int], int]] = None, orientation: Optional[Union[Var[str], str]] = None, min_h: Optional[Union[Var[str], str]] = None, min_w: Optional[Union[Var[str], str]] = None, max_h: Optional[Union[Var[str], str]] = None, max_w: Optional[Union[Var[str], str]] = None, **props) -> "Slider": ...  # type: ignore

class SliderTrack(ChakraComponent):
    @overload
    @classmethod
    def create(cls, *children, **props) -> "SliderTrack": ...  # type: ignore

class SliderFilledTrack(ChakraComponent):
    @overload
    @classmethod
    def create(cls, *children, **props) -> "SliderFilledTrack": ...  # type: ignore

class SliderThumb(ChakraComponent):
    @overload
    @classmethod
    def create(cls, *children, box_size: Optional[Union[Var[str], str]] = None, **props) -> "SliderThumb": ...  # type: ignore

class SliderMark(ChakraComponent):
    @overload
    @classmethod
    def create(cls, *children, **props) -> "SliderMark": ...  # type: ignore
