[supervisord]
nodaemon=true
user=root
logfile=$SB/apps/verify_upgrade/sup/a3/supervisord.log
pidfile=$SB/apps/verify_upgrade/sup/a3/supervisord.pid
childlogdir=$SB/apps/verify_upgrade/sup/a3
[inet_http_server]
port=127.0.0.1:8659
[supervisorctl]
serverurl=http://127.0.0.1:8659
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
[program:json_INT_pidonly]
command=$SB/envs/a3/bin/reflex run --json --frontend-port 3640 --backend-port 8640
directory=$SB/apps/verify_upgrade/blank_a3
environment=REFLEX_TELEMETRY_ENABLED="false"
autostart=false
autorestart=false
startsecs=1
stopsignal=INT
stopasgroup=false
killasgroup=false
stopwaitsecs=10
stdout_logfile=$SB/apps/verify_upgrade/sup/a3/json_INT_pidonly.out.log
stderr_logfile=$SB/apps/verify_upgrade/sup/a3/json_INT_pidonly.err.log
[program:json_INT_group]
command=$SB/envs/a3/bin/reflex run --json --frontend-port 3640 --backend-port 8640
directory=$SB/apps/verify_upgrade/blank_a3
environment=REFLEX_TELEMETRY_ENABLED="false"
autostart=false
autorestart=false
startsecs=1
stopsignal=INT
stopasgroup=true
killasgroup=true
stopwaitsecs=10
stdout_logfile=$SB/apps/verify_upgrade/sup/a3/json_INT_group.out.log
stderr_logfile=$SB/apps/verify_upgrade/sup/a3/json_INT_group.err.log
[program:json_TERM_default]
command=$SB/envs/a3/bin/reflex run --json --frontend-port 3640 --backend-port 8640
directory=$SB/apps/verify_upgrade/blank_a3
environment=REFLEX_TELEMETRY_ENABLED="false"
autostart=false
autorestart=false
startsecs=1
stopsignal=TERM
stopasgroup=false
killasgroup=false
stopwaitsecs=10
stdout_logfile=$SB/apps/verify_upgrade/sup/a3/json_TERM_default.out.log
stderr_logfile=$SB/apps/verify_upgrade/sup/a3/json_TERM_default.err.log
[program:plain_INT_pidonly]
command=$SB/envs/a3/bin/reflex run  --frontend-port 3640 --backend-port 8640
directory=$SB/apps/verify_upgrade/blank_a3
environment=REFLEX_TELEMETRY_ENABLED="false"
autostart=false
autorestart=false
startsecs=1
stopsignal=INT
stopasgroup=false
killasgroup=false
stopwaitsecs=10
stdout_logfile=$SB/apps/verify_upgrade/sup/a3/plain_INT_pidonly.out.log
stderr_logfile=$SB/apps/verify_upgrade/sup/a3/plain_INT_pidonly.err.log
