"""Scaffolding and drift-checking of the GitHub Actions workflows.

The workflows are copied into the consumer repository rather than referenced as
cross-repository reusable workflows: PyPI trusted publishing validates the OIDC
``job_workflow_ref`` claim, which points at the repository that owns the
workflow file, so a publish workflow living somewhere else cannot be trusted by
the project's own PyPI publisher.

``sync`` re-renders the templates from the repository's configuration, so an
upgrade is a version bump plus one command, and ``sync --check`` fails CI when a
scaffolded file drifts from what the installed version would generate.
"""

from __future__ import annotations

import difflib
import re
import subprocess
from importlib import metadata
from pathlib import Path

from .actions import echo, fail
from .config import Config, load_config, load_pyproject
from .versions import ACTIONS

WORKFLOW_DIR = ".github/workflows"

#: Workflows every consumer repository gets.
CORE_WORKFLOWS = (
    "changelog.yml",
    "dispatch_release.yml",
    "release_from_changelog.yml",
    "publish.yml",
)

#: Workflow scaffolded only for repositories that declare internal packages.
INTERNAL_WORKFLOW = "auto_release_internal.yml"

TEMPLATE_DIR = Path(__file__).parent / "templates" / "workflows"

_GITHUB_REMOTE_RE = re.compile(
    r"github\.com[:/](?P<owner>[^/]+)/(?P<repo>[^/]+?)(?:\.git)?$"
)

TOWNCRIER_TYPES = (
    ("breaking", "Breaking Changes"),
    ("deprecation", "Deprecations"),
    ("feature", "Features"),
    ("bugfix", "Bug Fixes"),
    ("performance", "Performance"),
    ("docs", "Documentation"),
    ("misc", "Miscellaneous"),
)


def installed_version() -> str:
    """Return the installed version of this package.

    Returns:
        The distribution version, or ``0.0.0`` when it cannot be determined
        (running from a source tree without an installed distribution).
    """
    try:
        return metadata.version("reflex-release")
    except metadata.PackageNotFoundError:
        return "0.0.0"


def default_cli_command(pin: str | None) -> str:
    """Return the invocation the scaffolded workflows should use.

    Args:
        pin: An explicit version to pin, ``""`` to leave the tool unpinned, or
            None to pin the installed version when it looks published.

    Returns:
        The command, e.g. ``uvx reflex-release@1.2.3``.
    """
    if pin is None:
        version = installed_version()
        pin = "" if version.startswith("0.0.0") else version
    return f"uvx reflex-release@{pin}" if pin else "uvx reflex-release"


def managed_workflows(config: Config) -> tuple[str, ...]:
    """List the workflow files this tool generates for a repository.

    Args:
        config: The repository configuration.

    Returns:
        The workflow filenames.
    """
    if config.internal_packages:
        return (*CORE_WORKFLOWS, INTERNAL_WORKFLOW)
    return CORE_WORKFLOWS


def _indented_list(items: list[str], indent: int) -> str:
    """Render a YAML sequence of scalars at a fixed indentation.

    Args:
        items: The scalar values.
        indent: The number of leading spaces per line.

    Returns:
        The rendered block, without a trailing newline.
    """
    return "\n".join(f"{' ' * indent}- {item}" for item in items)


def render(name: str, config: Config) -> str:
    """Render one workflow template for a repository.

    Args:
        name: The workflow filename.
        config: The repository configuration.

    Returns:
        The rendered YAML.
    """
    cli = config.cli_command
    header = "\n".join([
        "# Generated by reflex-release; do not edit by hand.",
        f"# Re-run `{cli} sync` after changing [tool.reflex-release] in",
        f"# pyproject.toml. `{cli} sync --check` fails when this file drifts.",
    ])
    internal_paths = [
        f'"{config.package_dir(package)}/**"' for package in config.internal_packages
    ]
    substitutions = {
        "@@HEADER@@": header,
        "@@CLI@@": cli,
        "@@MAIN_BRANCH@@": config.main_branch,
        "@@PRERELEASE_PREFIX@@": config.prerelease_branch_prefix,
        "@@HOTFIX_PREFIX@@": config.hotfix_branch_prefix,
        "@@RELEASE_PREFIX@@": config.release_branch_prefix,
        "@@ACTION_OPTIONS@@": _indented_list(list(ACTIONS), 10),
        "@@INTERNAL_PATHS@@": _indented_list(internal_paths, 6),
    }
    text = (TEMPLATE_DIR / name).read_text()
    for placeholder, value in substitutions.items():
        text = text.replace(placeholder, value)
    if remaining := re.findall(r"@@[A-Z_]+@@", text):
        fail(
            f"unsubstituted placeholder(s) in {name}: {', '.join(sorted(set(remaining)))}"
        )
    return text


def sync(config: Config, check: bool = False, force: bool = False) -> None:
    """Write the scaffolded workflows, or verify they are up to date.

    Args:
        config: The repository configuration.
        check: Report drift and fail instead of writing.
        force: Overwrite files that were not generated by this tool.
    """
    workflow_dir = config.root / WORKFLOW_DIR
    stale: list[str] = []
    for name in managed_workflows(config):
        target = workflow_dir / name
        rendered = render(name, config)
        current = target.read_text() if target.is_file() else None
        if current == rendered:
            continue
        if check:
            stale.append(name)
            echo(f"::group::{WORKFLOW_DIR}/{name} is out of date")
            echo(
                "".join(
                    difflib.unified_diff(
                        (current or "").splitlines(keepends=True),
                        rendered.splitlines(keepends=True),
                        fromfile=f"a/{WORKFLOW_DIR}/{name}",
                        tofile=f"b/{WORKFLOW_DIR}/{name}",
                    )
                )
            )
            echo("::endgroup::")
            continue
        if (
            current is not None
            and "Generated by reflex-release" not in current
            and not force
        ):
            fail(
                f"{WORKFLOW_DIR}/{name} exists and was not generated by "
                "reflex-release; move it aside or re-run with --force"
            )
        workflow_dir.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered)
        echo(f"{'updated' if current else 'wrote'} {WORKFLOW_DIR}/{name}")

    if stale:
        fail(
            f"{len(stale)} scaffolded workflow(s) are out of date: "
            f"{', '.join(stale)}. Run `{config.cli_command} sync` and commit the result."
        )
    if check:
        echo(
            f"All {len(managed_workflows(config))} scaffolded workflows are up to date."
        )


def _github_slug(root: Path) -> str | None:
    """Return the ``owner/repo`` slug of the origin remote, if it is on GitHub.

    Args:
        root: The repository root.

    Returns:
        The slug, or None when it cannot be determined.
    """
    result = subprocess.run(
        ["git", "remote", "get-url", "origin"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        return None
    match = _GITHUB_REMOTE_RE.search(result.stdout.strip())
    return f"{match['owner']}/{match['repo']}" if match else None


def release_config_toml(root: Path, cli_command: str) -> str:
    """Render a starter ``[tool.reflex-release]`` table for a repository.

    Args:
        root: The repository root.
        cli_command: The invocation the workflows should use.

    Returns:
        The TOML text to append to ``pyproject.toml``.
    """
    project = load_pyproject(root / "pyproject.toml").get("project", {})
    lines = [
        "[tool.reflex-release]",
        f'cli-command = "{cli_command}"',
    ]
    if name := project.get("name"):
        lines.append(f'root-package = "{name}"')
    if (root / "packages").is_dir():
        lines.append('packages-dir = "packages"')
    lines.append('release-timezone = "UTC"')
    return "\n".join(lines) + "\n"


def towncrier_config_toml(root: Path) -> str:
    """Render the shared ``[tool.towncrier]`` configuration for a repository.

    The ``package``/``name`` keys are intentionally empty: every invocation
    passes ``--dir <package path>`` to target one package, which is how a single
    configuration serves a whole monorepo.

    Args:
        root: The repository root.

    Returns:
        The TOML text to append to ``pyproject.toml``.
    """
    slug = _github_slug(root) or "OWNER/REPO"
    lines = [
        "[tool.towncrier]",
        "# One shared configuration for every package: each invocation passes",
        "# --dir <package path> to target a specific package's news/ directory.",
        "# https://towncrier.readthedocs.io/en/stable/monorepo.html",
        'package = ""',
        'name = ""',
        'directory = "news"',
        'filename = "CHANGELOG.md"',
        'title_format = "## {version} ({project_date})"',
        f'issue_format = "[#{{issue}}](https://github.com/{slug}/issues/{{issue}})"',
        'start_string = "<!-- towncrier release notes start -->\\n"',
    ]
    for directory, display in TOWNCRIER_TYPES:
        lines += [
            "",
            "[[tool.towncrier.type]]",
            f'directory = "{directory}"',
            f'name = "{display}"',
            "showcontent = true",
        ]
    return "\n".join(lines) + "\n"


def _append_table(pyproject: Path, table: str, text: str) -> bool:
    """Append a configuration table to ``pyproject.toml`` when it is absent.

    Args:
        pyproject: The file to update.
        table: The table name to look for (e.g. ``tool.towncrier``).
        text: The TOML text to append.

    Returns:
        True when the table was appended, False when it already existed.
    """
    current = pyproject.read_text()
    if re.search(rf"^\[+{re.escape(table)}[.\]]", current, re.MULTILINE):
        echo(f"[{table}] already configured; leaving it untouched.")
        return False
    separator = (
        "" if current.endswith("\n\n") else "\n" if current.endswith("\n") else "\n\n"
    )
    pyproject.write_text(current + separator + text)
    echo(f"added [{table}] to pyproject.toml")
    return True


def init(root: Path, pin: str | None, force: bool) -> None:
    """Set up changelog-driven releases in a repository.

    Adds the configuration tables when they are missing, creates the ``news``
    directories and writes the workflows.

    Args:
        root: The repository root.
        pin: Version to pin the workflows to (None auto-detects, ``""`` leaves
            the tool unpinned).
        force: Overwrite workflow files not generated by this tool.
    """
    pyproject = root / "pyproject.toml"
    if not pyproject.is_file():
        fail(f"no pyproject.toml in {root}; run this from the repository root")

    cli_command = default_cli_command(pin)
    _append_table(
        pyproject, "tool.reflex-release", release_config_toml(root, cli_command)
    )
    _append_table(pyproject, "tool.towncrier", towncrier_config_toml(root))

    config = load_config(root)
    for package in config.all_packages():
        if config.is_internal(package):
            continue
        news = config.news_dir(package)
        news.mkdir(parents=True, exist_ok=True)
        keep = news / ".gitkeep"
        if not any(news.iterdir()):
            keep.touch()
        echo(f"news directory ready: {news.relative_to(root).as_posix()}")

    sync(config, force=force)
    print_checklist(config)


def print_checklist(config: Config) -> None:
    """Print the repository settings that must be configured by hand.

    Args:
        config: The repository configuration.
    """
    echo(
        "\n".join([
            "",
            "Remaining setup (GitHub settings, once per repository):",
            "  1. Create the `pypi` environment and add required reviewers to it.",
            "     Every upload — alphas included — waits for that approval.",
            "  2. Configure PyPI trusted publishing for each distribution:",
            "     workflow `publish.yml`, environment `pypi`.",
            "  3. Enable 'Allow GitHub Actions to create and approve pull requests'",
            "     in Settings -> Actions -> General.",
            "  4. Create the `skip-changelog` and `changelog-version-edit` labels.",
            f"  5. Protect `{config.main_branch}` and restrict who may push",
            (
                f"     `{config.prerelease_branch_prefix}**`, "
                f"`{config.hotfix_branch_prefix}**` and "
                f"`{config.release_branch_prefix}**`"
            ),
            "     to maintainers plus the github-actions[bot] app.",
            "  6. Give every package a version derived from git tags (see the README",
            "     section 'Tag-derived versions').",
            "",
            "Then cut a release from the Actions tab: Dispatch release.",
        ])
    )
