"""Stub file for stack.py"""
# ------------------- DO NOT EDIT ----------------------
# This file was generated by `scripts/pyi_generator.py`!
# ------------------------------------------------------

from typing import Union, overload, Optional
from reflex.components.libs.chakra import ChakraComponent
from reflex.components.component import Component
from reflex.vars import Var, BaseVar, ComputedVar
from reflex.event import EventChain

class Stack(ChakraComponent):
    @overload
    @classmethod
    def create(cls, *children, align_items: Optional[Union[Var[str], str]] = None, direction: Optional[Union[Var[str], str]] = None, is_inline: Optional[Union[Var[bool], bool]] = None, justify_content: Optional[Union[Var[str], str]] = None, should_wrap_children: Optional[Union[Var[bool], bool]] = None, spacing: Optional[Union[Var[str], str]] = None, wrap: Optional[Union[Var[str], str]] = None, justify: Optional[Union[Var[str], str]] = None, **props) -> "Stack": ...  # type: ignore

class Hstack(Stack):
    @overload
    @classmethod
    def create(cls, *children, **props) -> "Hstack": ...  # type: ignore

class Vstack(Stack):
    @overload
    @classmethod
    def create(cls, *children, **props) -> "Vstack": ...  # type: ignore
