"""Stub file for document.py"""
# ------------------- DO NOT EDIT ----------------------
# This file was generated by `scripts/pyi_generator.py`!
# ------------------------------------------------------

from typing import Union, overload, Optional
from reflex.components.libs.chakra import ChakraComponent
from reflex.components.component import Component
from reflex.vars import Var, BaseVar, ComputedVar
from reflex.event import EventChain

class NextDocumentLib(Component):
    @overload
    @classmethod
    def create(cls, *children, **props) -> "NextDocumentLib": ...  # type: ignore

class Html(NextDocumentLib):
    @overload
    @classmethod
    def create(cls, *children, **props) -> "Html": ...  # type: ignore

class DocumentHead(NextDocumentLib):
    @overload
    @classmethod
    def create(cls, *children, **props) -> "DocumentHead": ...  # type: ignore

class Main(NextDocumentLib):
    @overload
    @classmethod
    def create(cls, *children, **props) -> "Main": ...  # type: ignore

class NextScript(NextDocumentLib):
    @overload
    @classmethod
    def create(cls, *children, **props) -> "NextScript": ...  # type: ignore

class ColorModeScript(ChakraComponent):
    @overload
    @classmethod
    def create(cls, *children, **props) -> "ColorModeScript": ...  # type: ignore
