name: e2e-cli-deploy-reflex-web-to-dev
on:
  # pull_request:
  #   branches: [main]
  #   paths:
  #     - '.github/workflows/e2e_cli_deploy_reflex_web_to_dev.yml'
  #     - '.github/actions/cli_deploy_reflex_app/action.yml'
  #     - 'reflex_cli/**'
  #     - 'pyproject.yml'
  #     - 'poetry.lock'
  # push:
  #   branches: [main]
  #   paths:
  #     - '.github/workflows/e2e_cli_deploy_reflex_web_to_dev.yml'
  #     - 'reflex_cli/**'
  #     - 'pyproject.yml'
  #     - 'poetry.lock'
  workflow_dispatch:
    inputs:
      reflex-web-ref:
        description: 'reflex-web ref to deploy'
        required: true
        default: 'main'
      reflex-hosting-cli-ref:
        description: 'reflex-hosting-cli ref to use'
        required: true
        default: 'main'
      reflex-pin:
        description: 'Reflex pin (@, ==, all ok)'

jobs:
  e2e-cli-deploy-reflex-web-to-dev:
    runs-on: Ubuntu-8-32
    timeout-minutes: 20
    env:
      TELEMETRY_ENABLED: false
      DEPLOYMENT_KEY: pcweb-${{ github.run_id }}-${{ github.run_attempt }}
      REFLEX_HOSTING_CLI_PATH: reflex-hosting-cli
    steps:
      - name: Check out reflex-hosting-cli repo
        uses: actions/checkout@v3
        with:
          repository: reflex-dev/reflex-hosting-cli
          ref: ${{ inputs.reflex-hosting-cli-ref }}
      - name: Deploy reflex-web
        uses: ./.github/actions/cli_deploy_reflex_app
        with:
          reflex-app-repo: reflex-dev/reflex-web
          deployment-key: ${DEPLOYMENT_KEY}
          reflex-pin: '@git+https://github.com/reflex-dev/reflex@main'
          cp-web-url: ${{ secrets.DEV_CP_WEB_URL }}
          cp-backend-url: ${{ secrets.DEV_CP_BACKEND_URL }}
          cp-env: 'dev'
          user-email: ${{ secrets.DEV_CI_TEST_USER_EMAIL }}
          user-password: ${{ secrets.DEV_CI_TEST_USER_PASSWORD }}
      - name: Delete reflex-web deployment in dev
        shell: bash
        env:
          REFLEX_CLOUD_URL: ${{ secrets.DEV_CP_WEB_URL }}
          REFLEX_CLOUD_BACKEND_URL: ${{ secrets.DEV_CP_BACKEND_URL }}
        run: |
          source venv/bin/activate
          reflex deployments delete ${DEPLOYMENT_KEY}
