# Sourced from https://developer.mozilla.org/en-US/docs/Web/HTML/Element.
from collections import defaultdict


ELEMENTS = """
html base head link meta style title body address article aside
footer header h1 h2 h3 h4 h5 h6 main nav section blockquote dd
div dl dt figcaption figure hr li menu ol p pre ul a abbr b bdi
bdo br cite code data dfn em i kbd mark q rp rt ruby s samp
small span strong sub sup time u var wbr area audio img map
track video embed iframe object picture portal source svg math
canvas noscript script del ins caption col colgroup table tbody
td tfoot th thead tr button datalist fieldset form input label
legend meter optgroup option output progress select textarea
details dialog summary slot template
""".split()

# Sources:
# - https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
# - https://github.com/facebook/react/blob/d1ad984db1591b131d16739a24dee4ba44886a09/packages/react-dom-bindings/src/shared/DOMProperty.js.
# TODO: Support data-* and aria-* attributes.

PROP_TO_ELEMENTS = {
    "accept": ["form", "input"],
    "acceptCharset": ["form"],  # Renamed from "accept-charset".
    "accesskey": ELEMENTS,
    "action": ["form"],
    "align": [
        "applet",
        "caption",
        "col",
        "colgroup",
        "hr",
        "iframe",
        "img",
        "table",
        "tbody",
        "td",
        "tfoot",
        "th",
        "thead",
        "tr",
    ],
    "allow": ["iframe"],
    "alt": ["applet", "area", "img", "input"],
    "async": ["script"],
    "autocapitalize": ELEMENTS,
    "autocomplete": ["form", "input", "select", "textarea"],
    "autofocus": ["button", "input", "keygen", "select", "textarea"],
    "autoplay": ["audio", "video"],
    "background": ["body", "table", "td", "th"],
    "bgcolor": [
        "body",
        "col",
        "colgroup",
        "marquee",
        "table",
        "tbody",
        "tfoot",
        "td",
        "th",
        "tr",
    ],
    "border": ["img", "object", "table"],
    "buffered": ["audio", "video"],
    "capture": ["input"],
    "challenge": ["keygen"],
    "charset": ["meta", "script"],
    "checked": ["input"],
    "cite": ["blockquote", "del", "ins", "q"],
    # "class": ELEMENTS,  # Omitted; already defined in Component.
    "code": ["applet"],
    "codebase": ["applet"],
    "color": ["font", "hr"],
    "cols": ["textarea"],
    "colspan": ["td", "th"],
    "content": ["meta"],
    "contenteditable": ELEMENTS,
    "contextmenu": ELEMENTS,
    "controls": ["audio", "video"],
    "coords": ["area"],
    "crossorigin": ["audio", "img", "link", "script", "video"],
    "csp": ["iframe"],
    "data": ["object"],
    "datetime": ["del", "ins", "time"],
    "decoding": ["img"],
    "default": ["track"],
    "defer": ["script"],
    "dir": ELEMENTS,
    "dirname": ["input", "textarea"],
    "disabled": [
        "button",
        "fieldset",
        "input",
        "keygen",
        "optgroup",
        "option",
        "select",
        "textarea",
    ],
    "download": ["a", "area"],
    "draggable": ELEMENTS,
    "enctype": ["form"],
    "enterkeyhint": ELEMENTS,
    "htmlFor": ["label", "output"],  # Renamed from "for".
    "form": [
        "button",
        "fieldset",
        "input",
        "keygen",
        "label",
        "meter",
        "object",
        "output",
        "progress",
        "select",
        "textarea",
    ],
    "formaction": ["button", "input"],
    "formenctype": ["button", "input"],
    "formmethod": ["button", "input"],
    "formnovalidate": ["button", "input"],
    "formtarget": ["button", "input"],
    "headers": ["td", "th"],
    "height": ["canvas", "embed", "iframe", "img", "input", "object", "video"],
    "hidden": ELEMENTS,
    "high": ["meter"],
    "href": ["a", "area", "base", "link"],
    "hreflang": ["a", "area", "link"],
    "httpEquiv": ["meta"],  # Renamed from "http-equiv".
    "icon": ["command"],
    "id": ELEMENTS,
    "integrity": ["link", "script"],
    "intrinsicsize": ["img"],
    "inputmode": ELEMENTS,
    "ismap": ["img"],
    "itemprop": ELEMENTS,
    "keytype": ["keygen"],
    "kind": ["track"],
    "label": ["optgroup", "option", "track"],
    "lang": ELEMENTS,
    "language": ["script"],
    "loading": ["img", "iframe"],
    "list": ["input"],
    "loop": ["audio", "bgsound", "marquee", "video"],
    "low": ["meter"],
    "manifest": ["html"],
    "max": ["input", "meter", "progress"],
    "maxlength": ["input", "textarea"],
    "minlength": ["input", "textarea"],
    "media": ["a", "area", "link", "source", "style"],
    "method": ["form"],
    "min": ["input", "meter"],
    "multiple": ["input", "select"],
    "muted": ["audio", "video"],
    "name": [
        "button",
        "form",
        "fieldset",
        "iframe",
        "input",
        "keygen",
        "object",
        "output",
        "select",
        "textarea",
        "map",
        "meta",
        "param",
    ],
    "novalidate": ["form"],
    "open": ["details", "dialog"],
    "optimum": ["meter"],
    "pattern": ["input"],
    "ping": ["a", "area"],
    "placeholder": ["input", "textarea"],
    "playsinline": ["video"],
    "poster": ["video"],
    "preload": ["audio", "video"],
    "readonly": ["input", "textarea"],
    "referrerpolicy": ["a", "area", "iframe", "img", "link", "script"],
    "rel": ["a", "area", "link"],
    "required": ["input", "select", "textarea"],
    "reversed": ["ol"],
    "role": ELEMENTS,
    "rows": ["textarea"],
    "rowspan": ["td", "th"],
    "sandbox": ["iframe"],
    "scope": ["th"],
    "scoped": ["style"],
    "selected": ["option"],
    "shape": ["a", "area"],
    "size": ["input", "select"],
    "sizes": ["link", "img", "source"],
    "slot": ELEMENTS,
    "span": ["col", "colgroup"],
    "spellcheck": ELEMENTS,
    "src": [
        "audio",
        "embed",
        "iframe",
        "img",
        "input",
        "script",
        "source",
        "track",
        "video",
    ],
    "srcdoc": ["iframe"],
    "srclang": ["track"],
    "srcset": ["img", "source"],
    "start": ["ol"],
    "step": ["input"],
    "style": ELEMENTS,
    "summary": ["table"],
    "tabindex": ELEMENTS,
    "target": ["a", "area", "base", "form"],
    "title": ELEMENTS,
    "translate": ELEMENTS,
    "type": [
        "button",
        "input",
        "embed",
        "object",
        "ol",
        "script",
        "source",
        "style",
        "menu",
        "link",
    ],
    "usemap": ["img", "input", "object"],
    "value": [
        "button",
        "data",
        "input",
        "li",
        "meter",
        "option",
        "progress",
        "param",
    ],
    "width": ["canvas", "embed", "iframe", "img", "input", "object", "video"],
    "wrap": ["textarea"],
}


ELEMENT_TO_PROPS = defaultdict(list)
for prop, els in PROP_TO_ELEMENTS.items():
    for el in els:
        ELEMENT_TO_PROPS[el].append(prop)
