name: whitelist check

on:
  pull_request:

permissions:
  contents: read

jobs:
  reflex-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Assert whitelist is empty
        run: echo -e "\nassert not WHITELISTED_PAGES, f'WHITELISTED_PAGES includes {WHITELISTED_PAGES}'" | cat "reflex_docs/whitelist.py" - | python3
