"""Tests for reflex_release.scaffold."""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest
import yaml
from reflex_release.actions import ReleaseError
from reflex_release.commands import _split_selection
from reflex_release.config import (
    DEFAULT_PYTHON_VERSION,
    DEFAULT_UV_VERSION,
    POST_RELEASE_INPUTS,
    Config,
    load_config,
)
from reflex_release.scaffold import (
    CORE_WORKFLOWS,
    CUSTOM_BUILD_CONTRACT,
    CUSTOM_BUILD_INPUTS,
    GENERATED_WORKFLOWS,
    INTERNAL_WORKFLOW,
    MAX_DISPATCH_CHECKBOXES,
    TEMPLATE_DIR,
    WORKFLOW_DIR,
    default_cli_command,
    dispatch_inputs,
    generated_workflow_names,
    init,
    managed_workflows,
    render,
    sync,
    towncrier_config_toml,
    use_checkboxes,
    workflow_call_inputs,
)
from reflex_release.versions import ACTIONS

from .conftest import set_post_release_workflow, write_custom_build, write_lockstep


def test_render_substitutes_every_placeholder(config: Config) -> None:
    for name in CORE_WORKFLOWS:
        rendered = render(name, config)
        assert not re.search(r"@@[A-Z_]+@@", rendered)
        assert "Generated by reflex-release" in rendered


#: The actions the generated workflows install uv and the repository with.
_UV_ACTION = "astral-sh/setup-uv@"
_CHECKOUT_ACTION = "actions/checkout@"

#: The setup-uv step, and the placeholders one of which has to follow it so the
#: configured pins reach it. Which of the two belongs on a given step depends on
#: whether its job checked out, which test_render_quiets_setup_uv_only_where_
#: there_is_no_checkout enforces against the rendered YAML.
_UV_SETUP = f"uses: {_UV_ACTION}"
_UV_SETUP_PLACEHOLDERS = ("@@UV_SETUP_WITH@@", "@@UV_SETUP_NO_CHECKOUT@@")

#: What the checkout-less block passes on top of the pins, to keep setup-uv from
#: warning about a working directory that is empty on purpose.
_QUIET_SETUP = {"enable-cache": "false", "ignore-empty-workdir": "true"}


def test_every_template_pins_the_uv_it_installs() -> None:
    """Each setup-uv step must be followed by a pin placeholder.

    render() only fails on a placeholder it could not substitute, so a step
    added to a template without one would silently install an unpinned uv.
    """
    found = 0
    for template in sorted(TEMPLATE_DIR.glob("*.yml")):
        lines = template.read_text(encoding="utf-8").splitlines()
        for index, line in enumerate(lines):
            if _UV_SETUP not in line:
                continue
            found += 1
            assert lines[index + 1] in _UV_SETUP_PLACEHOLDERS, (
                f"{template.name} line {index + 1} installs uv without one of the "
                f"{', '.join(_UV_SETUP_PLACEHOLDERS)} lines that pin it"
            )
    assert found, "no template installs uv; the placeholder guard is checking nothing"


def _uv_steps_by_checkout(rendered: str) -> tuple[list[dict], list[dict]]:
    """Split a rendered workflow's setup-uv steps by what their job checked out.

    Args:
        rendered: A rendered workflow.

    Returns:
        The ``uses: astral-sh/setup-uv`` step mappings of the jobs that check the
        repository out, then those of the jobs that do not.
    """
    checked_out: list[dict] = []
    bare: list[dict] = []
    for job in yaml.safe_load(rendered)["jobs"].values():
        steps = job.get("steps") or []
        group = (
            checked_out
            if any(_CHECKOUT_ACTION in step.get("uses", "") for step in steps)
            else bare
        )
        group += [step for step in steps if _UV_ACTION in step.get("uses", "")]
    return checked_out, bare


def test_render_quiets_setup_uv_only_where_there_is_no_checkout(
    config: Config,
) -> None:
    """The quieting block belongs on the jobs with an empty workspace, and only there.

    setup-uv hashes the working directory for its cache key and checks that the
    directory is not empty; a job that installs uv without a checkout (the gated
    publish job) trips both, for a cache it has no dependencies to fill. A job
    that did check out has files to hash and dependencies to install, so the same
    block there would quietly turn a cache it wants off.
    """
    found = 0
    for name in GENERATED_WORKFLOWS:
        checked_out, bare = _uv_steps_by_checkout(render(name, config))
        found += len(bare)
        for step in bare:
            assert _QUIET_SETUP.items() <= step["with"].items(), name
        for step in checked_out:
            assert not _QUIET_SETUP.keys() & (step.get("with") or {}).keys(), name
    assert found, "no job installs uv without a checkout; this guard checks nothing"


def test_render_pins_uv_and_python(config: Config) -> None:
    for name in CORE_WORKFLOWS:
        rendered = render(name, config)
        steps = rendered.count(_UV_SETUP)
        assert steps
        assert rendered.count(f'          version: "{DEFAULT_UV_VERSION}"') == steps
        assert (
            rendered.count(f'          python-version: "{DEFAULT_PYTHON_VERSION}"')
            == steps
        )


@pytest.mark.parametrize(
    ("body", "expected", "absent"),
    [
        ('uv-version = "9.9.9"', '          version: "9.9.9"', "0.12.5"),
        ('python-version = "3.11"', '          python-version: "3.11"', "3.14"),
        ('uv-version = ""', '          python-version: "', '          version: "'),
    ],
)
def test_render_honors_configured_pins(
    repo: Path, body: str, expected: str, absent: str
) -> None:
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'packages-dir = "packages"', f'packages-dir = "packages"\n{body}'
        ),
        encoding="utf-8",
    )
    rendered = render("publish.yml", load_config(repo))
    assert expected in rendered
    assert absent not in rendered


def test_render_omits_the_block_when_nothing_is_pinned(repo: Path) -> None:
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'packages-dir = "packages"',
            'packages-dir = "packages"\nuv-version = ""\npython-version = ""',
        ),
        encoding="utf-8",
    )
    rendered = render("publish.yml", load_config(repo))
    lines = rendered.splitlines()
    steps = [index for index, line in enumerate(lines) if _UV_SETUP in line]
    assert steps
    # The placeholder line goes away entirely rather than leaving a `with:` with
    # nothing under it, and takes its own newline with it rather than opening a
    # gap in the step list. The checkout-less job keeps its block: what that one
    # passes silences setup-uv rather than pinning it.
    _, bare = _uv_steps_by_checkout(rendered)
    assert sum(1 for index in steps if lines[index + 1].strip() == "with:") == len(bare)
    for step in bare:
        assert set(step["with"]) == set(_QUIET_SETUP)
    assert "\n\n\n" not in rendered
    yaml.safe_load(rendered)


def test_render_uses_the_configured_branches(config: Config, repo: Path) -> None:
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'packages-dir = "packages"',
            'packages-dir = "packages"\nmain-branch = "trunk"\nprerelease-branch-prefix = "pre/"',
        ),
        encoding="utf-8",
    )
    rendered = render("release_from_changelog.yml", load_config(repo))
    assert 'branches: ["trunk", "pre/**", "r/hotfix/**"]' in rendered


def test_render_lists_every_release_action(config: Config) -> None:
    rendered = render("dispatch_release.yml", config)
    for action in ACTIONS:
        assert f"          - {action}\n" in rendered


def test_render_uses_the_pinned_cli_command(config: Config, repo: Path) -> None:
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            "[tool.reflex-release]",
            '[tool.reflex-release]\ncli-command = "uvx reflex-release@1.2.3"',
        ),
        encoding="utf-8",
    )
    assert "uvx reflex-release@1.2.3 detect" in render(
        "release_from_changelog.yml", load_config(repo)
    )


def test_internal_workflow_is_only_generated_when_configured(
    config: Config, repo: Path
) -> None:
    assert managed_workflows(config) == CORE_WORKFLOWS
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'packages-dir = "packages"',
            'packages-dir = "packages"\ninternal-packages = ["widget-core"]',
        ),
        encoding="utf-8",
    )
    reloaded = load_config(repo)
    assert managed_workflows(reloaded) == (*CORE_WORKFLOWS, INTERNAL_WORKFLOW)
    # The trigger matches what detect-internal counts as the package's source.
    assert '- "packages/widget-core/src/**"' in render(INTERNAL_WORKFLOW, reloaded)


def add_internal(repo: Path, package: str) -> Config:
    """Mark a package as internal and reload the configuration.

    Args:
        repo: The repository root.
        package: The package to list in ``internal-packages``.

    Returns:
        The reloaded configuration.
    """
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'packages-dir = "packages"',
            f'packages-dir = "packages"\ninternal-packages = ["{package}"]',
        ),
        encoding="utf-8",
    )
    return load_config(repo)


def add_packages(repo: Path, *names: str) -> Config:
    """Add sub-packages to the temporary repository and reload its config.

    Args:
        repo: The repository root.
        *names: The sub-package directory names to create.

    Returns:
        The reloaded configuration.
    """
    for name in names:
        directory = repo / "packages" / name
        (directory / "src").mkdir(parents=True)
        (directory / "pyproject.toml").write_text(
            f'[project]\nname = "{name}"\n', encoding="utf-8"
        )
    return load_config(repo)


def test_never_published_packages_get_no_dispatch_checkbox(
    config: Config, repo: Path
) -> None:
    assert [entry.packages for entry in dispatch_inputs(config)] == [
        ("mypkg",),
        ("widget-core",),
    ]
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'packages-dir = "packages"',
            'packages-dir = "packages"\nnever-publish-packages = ["widget-core"]',
        ),
        encoding="utf-8",
    )
    reloaded = load_config(repo)
    assert [entry.packages for entry in dispatch_inputs(reloaded)] == [("mypkg",)]
    rendered = render("dispatch_release.yml", reloaded)
    assert "widget-core" not in rendered


@pytest.mark.parametrize("mode", ["checkboxes", "text"])
def test_rendered_workflows_are_valid_yaml(
    config: Config, repo: Path, mode: str
) -> None:
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            "[tool.reflex-release]",
            f'[tool.reflex-release]\ndispatch-package-inputs = "{mode}"',
        ),
        encoding="utf-8",
    )
    reloaded = load_config(repo)
    for name in managed_workflows(reloaded):
        document = yaml.safe_load(render(name, reloaded))
        assert document["jobs"], name


def test_every_generated_run_step_pins_the_shell(config: Config, repo: Path) -> None:
    """A default shell must not get to reinterpret a release-critical script."""
    write_custom_build(repo)
    add_internal(repo, "widget-core")
    reloaded = set_post_release_workflow(repo, "post_release.yml")
    steps = 0
    for name in managed_workflows(reloaded):
        for job in yaml.safe_load(render(name, reloaded))["jobs"].values():
            for step in job.get("steps", ()):
                if "run" not in step:
                    continue
                steps += 1
                assert step.get("shell") == "bash", (name, step.get("name"))
    assert steps


def test_dispatch_inputs_give_a_lockstep_group_one_checkbox(
    config: Config, repo: Path
) -> None:
    write_lockstep(repo)
    reloaded = load_config(repo)
    entries = dispatch_inputs(reloaded)
    assert [entry.input_id for entry in entries] == ["mypkg"]
    assert entries[0].packages == ("mypkg", "widget-core")
    assert entries[0].description == "mypkg (with widget-core)"


def test_checkboxes_select_every_member_of_a_lockstep_group(
    config: Config, repo: Path
) -> None:
    write_lockstep(repo)
    reloaded = load_config(repo)
    rendered = render("dispatch_release.yml", reloaded)
    assert "      mypkg:\n" in rendered
    assert "      widget_core:\n" not in rendered
    # The folded scalar must be indented past its key, or the YAML is invalid.
    packages = yaml.safe_load(rendered)["jobs"]["materialize"]["steps"][2]["env"][
        "PACKAGES"
    ]
    assert packages == "${{ inputs.mypkg && 'mypkg,widget-core' || '' }}"


def test_selection_parser_accepts_the_folded_scalar_shape() -> None:
    """The contract between the rendered PACKAGES scalar and the planner.

    GitHub folds the multi-line scalar into one space-separated line, and every
    unchecked box evaluates to an empty string.
    """
    assert _split_selection(" mypkg,widget-core  gadget ") == [
        "mypkg",
        "widget-core",
        "gadget",
    ]
    assert _split_selection("   ") == []


def test_auto_falls_back_to_free_text_past_the_input_limit(
    config: Config, repo: Path
) -> None:
    assert use_checkboxes(config)
    reloaded = add_packages(
        repo, *(f"pkg-{index}" for index in range(MAX_DISPATCH_CHECKBOXES))
    )
    assert len(dispatch_inputs(reloaded)) > MAX_DISPATCH_CHECKBOXES
    assert not use_checkboxes(reloaded)
    rendered = render("dispatch_release.yml", reloaded)
    assert "      packages:\n" in rendered
    assert (
        yaml.safe_load(rendered)["jobs"]["materialize"]["steps"][2]["env"]["PACKAGES"]
        == "${{ inputs.packages }}"
    )


def test_dispatch_package_inputs_can_be_forced(config: Config, repo: Path) -> None:
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            "[tool.reflex-release]",
            '[tool.reflex-release]\ndispatch-package-inputs = "text"',
        ),
        encoding="utf-8",
    )
    assert not use_checkboxes(load_config(repo))


def test_colliding_package_names_are_rejected(config: Config, repo: Path) -> None:
    reloaded = add_packages(repo, "widget_core")
    with pytest.raises(ReleaseError, match="collide as workflow inputs"):
        dispatch_inputs(reloaded)


def test_changelog_workflow_checks_for_workflow_drift(config: Config) -> None:
    assert "sync --check" in render("changelog.yml", config)


def test_sync_rejects_an_unparsable_title_format(config: Config, repo: Path) -> None:
    """A heading this tool writes but cannot read back would strand releases."""
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'title_format = "## {version} ({project_date})"',
            'title_format = "## Release {version} on {project_date}"',
        ),
        encoding="utf-8",
    )
    with pytest.raises(ReleaseError, match="cannot parse back"):
        sync(load_config(repo))


@pytest.mark.parametrize(
    "title_format", ["## {version} {bogus}", "## {0}", "## {version!x}"]
)
def test_sync_rejects_a_malformed_title_format(
    config: Config, repo: Path, title_format: str
) -> None:
    """The pull-request guard runs this, so it must give guidance, not a traceback."""
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'title_format = "## {version} ({project_date})"',
            f'title_format = "{title_format}"',
        ),
        encoding="utf-8",
    )
    with pytest.raises(ReleaseError, match="not a usable format string"):
        sync(load_config(repo))


def test_sync_accepts_a_custom_title_format_led_by_the_version(
    config: Config, repo: Path
) -> None:
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'title_format = "## {version} ({project_date})"',
            'title_format = "## {version} (released {project_date})"',
        ),
        encoding="utf-8",
    )
    sync(load_config(repo))


def test_sync_removes_an_obsolete_internal_workflow(config: Config, repo: Path) -> None:
    reloaded = add_internal(repo, "widget-core")
    sync(reloaded)
    target = repo / WORKFLOW_DIR / INTERNAL_WORKFLOW
    assert target.is_file()

    # The last internal package is gone, so its auto-release trigger must go too.
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            '\ninternal-packages = ["widget-core"]', ""
        ),
        encoding="utf-8",
    )
    without = load_config(repo)
    with pytest.raises(ReleaseError, match="out of date"):
        sync(without, check=True)
    sync(without)
    assert not target.exists()


def test_sync_keeps_a_foreign_workflow_of_the_same_name(
    config: Config, repo: Path
) -> None:
    target = repo / WORKFLOW_DIR / INTERNAL_WORKFLOW
    target.parent.mkdir(parents=True)
    target.write_text("name: hand written\n", encoding="utf-8")
    sync(config)
    assert target.read_text(encoding="utf-8") == "name: hand written\n"


def test_internal_workflow_triggers_on_the_whole_directory_without_src(
    config: Config, repo: Path
) -> None:
    """A flat-layout package owns its whole directory, and the trigger says so."""
    flat = repo / "packages" / "flat"
    flat.mkdir()
    (flat / "pyproject.toml").write_text('[project]\nname = "flat"\n', encoding="utf-8")
    reloaded = add_internal(repo, "flat")
    assert '- "packages/flat/**"' in render(INTERNAL_WORKFLOW, reloaded)


def test_internal_root_package_triggers_on_its_source_paths(
    config: Config, repo: Path
) -> None:
    reloaded = add_internal(repo, "mypkg")
    assert '- "src/**"' in render(INTERNAL_WORKFLOW, reloaded)


def test_internal_root_package_without_source_dirs_is_rejected(
    config: Config, repo: Path
) -> None:
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'packages-dir = "packages"',
            'packages-dir = "packages"\ninternal-packages = ["mypkg"]\n'
            "root-source-dirs = []",
        ),
        encoding="utf-8",
    )
    with pytest.raises(ReleaseError, match="set root-source-dirs"):
        render(INTERNAL_WORKFLOW, load_config(repo))


def test_the_heading_guard_covers_every_publishing_branch(config: Config) -> None:
    """A merged version heading is a publish trigger wherever it lands."""
    document = yaml.safe_load(render("changelog.yml", config))
    guarded = set(document[True]["pull_request"]["branches"])
    publishing = set(
        yaml.safe_load(render("release_from_changelog.yml", config))[True]["push"][
            "branches"
        ]
    )
    assert publishing <= guarded


def _changelog_step(config: Config, name: str) -> dict:
    """Return one step of the generated changelog workflow, by name.

    Args:
        config: The repository configuration.
        name: The step's ``name``.

    Returns:
        The step mapping.
    """
    steps = yaml.safe_load(render("changelog.yml", config))["jobs"]["changelog"][
        "steps"
    ]
    return next(step for step in steps if step.get("name") == name)


def test_release_branch_exemption_requires_the_bot_author(config: Config) -> None:
    """A contributor picks their branch name; they cannot pick the PR author."""
    step = _changelog_step(config, "Reject manual changelog version headings")
    assert "startsWith(github.head_ref, 'release/')" in step["if"]
    assert "github.event.pull_request.user.login == 'github-actions[bot]'" in step["if"]


def test_the_changelog_check_reruns_when_labels_change(config: Config) -> None:
    """A verdict is only valid for the label set it was computed under.

    Both waiver labels are applied and removed after the last push, so the
    trigger has to cover label events — and every run has to compute the real
    verdict, since a job skipped by `if` reports a check branch protection
    counts as passing.
    """
    document = yaml.safe_load(render("changelog.yml", config))
    assert {"labeled", "unlabeled"} <= set(document[True]["pull_request"]["types"])
    # Nothing gates the job itself, so no run can report green without checking.
    assert "if" not in document["jobs"]["changelog"]


def test_the_changelog_check_reads_labels_from_the_api(config: Config) -> None:
    """A re-run replays the original event payload, where a new label is absent.

    Reading `github.event.pull_request.labels` would therefore keep failing a
    re-run until someone pushed, which is the whole reason the labels come from
    the API instead.
    """
    document = yaml.safe_load(render("changelog.yml", config))
    # Round-tripped so the comment explaining the choice is not what passes.
    assert "github.event.pull_request.labels" not in yaml.safe_dump(document)
    assert document["permissions"]["pull-requests"] == "read"
    labels = document["jobs"]["changelog"]["steps"][0]
    assert labels["id"] == "labels"
    # Before the checkout: the step needs `gh` and nothing from the tree.
    assert "gh api" in labels["run"]
    for name, output in (
        ("Reject manual changelog version headings", "version_edit"),
        ("Check for news fragments", "skip"),
    ):
        assert (
            f"steps.labels.outputs.{output} != 'true'"
            in _changelog_step(config, name)["if"]
        )


def test_dev_pin_gate_runs_after_the_lockstep_pin(config: Config) -> None:
    """The gate has to judge the metadata the build actually emits."""
    names = [step.get("name", "") for step in _job_steps(config, "build")]
    assert names.index("Pin lockstep siblings to exact versions") < names.index(
        "Reject development-release dependency pins"
    )


def test_sync_writes_then_verifies(config: Config, repo: Path) -> None:
    sync(config)
    for name in CORE_WORKFLOWS:
        assert (repo / WORKFLOW_DIR / name).is_file()
    sync(config, check=True)


def test_sync_check_detects_drift(config: Config, repo: Path) -> None:
    sync(config)
    target = repo / WORKFLOW_DIR / "publish.yml"
    target.write_text(
        target.read_text(encoding="utf-8").replace(
            "Publish to PyPI", "Publish somewhere"
        ),
        encoding="utf-8",
    )
    with pytest.raises(ReleaseError, match="out of date"):
        sync(config, check=True)


def test_sync_refuses_to_clobber_a_foreign_workflow(config: Config, repo: Path) -> None:
    target = repo / WORKFLOW_DIR / "publish.yml"
    target.parent.mkdir(parents=True)
    target.write_text("name: something else\n", encoding="utf-8")
    with pytest.raises(ReleaseError, match="not generated by reflex-release"):
        sync(config)
    sync(config, force=True)
    assert "Generated by reflex-release" in target.read_text(encoding="utf-8")


@pytest.mark.parametrize(
    ("pin", "expected"),
    [("1.2.3", "uvx reflex-release@1.2.3"), ("", "uvx reflex-release")],
)
def test_default_cli_command(pin: str, expected: str) -> None:
    assert default_cli_command(pin) == expected


def test_towncrier_config_uses_the_github_remote(repo: Path) -> None:
    from .conftest import git

    git(repo, "remote", "add", "origin", "https://github.com/acme/widgets.git")
    assert "https://github.com/acme/widgets/issues/{issue}" in towncrier_config_toml(
        repo
    )


def test_towncrier_config_falls_back_without_a_remote(repo: Path) -> None:
    assert "OWNER/REPO" in towncrier_config_toml(repo)


def test_init_sets_up_a_bare_repository(tmp_path: Path) -> None:
    (tmp_path / "src" / "solo").mkdir(parents=True)
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "solo"\n', encoding="utf-8"
    )
    init(tmp_path, pin="9.9.9", force=False)

    config = load_config(tmp_path)
    assert config.root_package == "solo"
    assert config.cli_command == "uvx reflex-release@9.9.9"
    assert (tmp_path / "news" / ".gitkeep").is_file()
    for name in CORE_WORKFLOWS:
        assert (tmp_path / WORKFLOW_DIR / name).is_file()
    sync(config, check=True)


def test_init_warns_when_the_release_path_is_unpinned(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    """An unpinned tool resolves whatever is newest inside privileged jobs."""
    (tmp_path / "src" / "solo").mkdir(parents=True)
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "solo"\n', encoding="utf-8"
    )
    init(tmp_path, pin="", force=False)
    assert "unpinned" in capsys.readouterr().out


def test_init_does_not_warn_when_pinned(
    tmp_path: Path, capsys: pytest.CaptureFixture
) -> None:
    (tmp_path / "src" / "solo").mkdir(parents=True)
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "solo"\n', encoding="utf-8"
    )
    init(tmp_path, pin="9.9.9", force=False)
    assert "unpinned" not in capsys.readouterr().out


def _approval_step(config: Config) -> dict:
    """Return the pypi environment assertion step of the publish workflow.

    Args:
        config: The repository configuration.

    Returns:
        The parsed step.
    """
    return yaml.safe_load(render("publish.yml", config))["jobs"]["publish"]["steps"][0]


def _job_steps(config: Config, job: str) -> list[dict]:
    """Return the steps of one job of the publish workflow.

    Args:
        config: The repository configuration.
        job: The job id.

    Returns:
        The parsed steps.
    """
    return yaml.safe_load(render("publish.yml", config))["jobs"][job]["steps"]


def _manifest_step(config: Config) -> dict:
    """Return the step that writes the checksum manifest.

    Args:
        config: The repository configuration.

    Returns:
        The parsed step.
    """
    return next(
        step
        for step in _job_steps(config, "collect")
        if "> SHA256SUMS" in step.get("run", "")
    )


def test_the_approver_sees_the_artifact_digests(config: Config) -> None:
    """The approval is only meaningful if what is being uploaded is visible."""
    assert "GITHUB_STEP_SUMMARY" in _manifest_step(config)["run"]


def test_the_manifest_verifies_downloaded_release_assets(config: Config) -> None:
    """It is attached to the release, so it has to name the files as downloaded."""
    # Written from inside dist/, so the entries are bare filenames rather than
    # dist/-prefixed paths that only resolve inside the build's workspace.
    assert "(cd dist && sha256sum -- *) > SHA256SUMS" in _manifest_step(config)["run"]
    verify = next(
        step
        for step in yaml.safe_load(render("publish.yml", config))["jobs"]["publish"][
            "steps"
        ]
        if "sha256sum -c" in step.get("run", "")
    )
    assert verify["run"] == "cd dist && sha256sum -c ../SHA256SUMS"


def test_verify_dist_is_told_which_package_it_is_checking(config: Config) -> None:
    """Lockstep siblings share a version, so the name is what tells them apart."""
    step = next(
        step
        for step in _job_steps(config, "collect")
        if step.get("run", "").endswith("verify-dist")
    )
    assert "PACKAGE" in step["env"]


def test_publish_workflow_always_requires_reviewers(config: Config) -> None:
    """Reviewers are the floor, whatever the self-review policy is."""
    assert "required_reviewers" in _approval_step(config)["run"]


def test_self_review_is_permitted_by_default(config: Config) -> None:
    step = _approval_step(config)
    assert step["env"]["ALLOW_SELF_REVIEW"] == "true"


def test_self_review_can_be_asserted_against(config: Config, repo: Path) -> None:
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            "[tool.reflex-release]",
            "[tool.reflex-release]\nallow-self-review = false",
        ),
        encoding="utf-8",
    )
    reloaded = load_config(repo)
    assert not reloaded.allow_self_review
    assert _approval_step(reloaded)["env"]["ALLOW_SELF_REVIEW"] == "false"


def test_publish_workflow_gates_on_reviewers_and_self_review(config: Config) -> None:
    """The approval is only a two-person rule if self-review is prevented."""
    step = _approval_step(config)
    assert "required_reviewers" in step["run"]
    assignment = next(
        line
        for line in step["run"].splitlines()
        if line.strip().startswith("self_review=")
    )
    # jq's // operator treats a literal false as absent, which would downgrade
    # the very case this check exists for into a warning.
    assert "prevent_self_review" in assignment
    assert "//" not in assignment
    # Strict mode is opt-in, so an unreadable setting is a failure, not a
    # warning: "the API did not say" cannot be distinguished from "allowed".
    assert '"$self_review" != "true"' in step["run"]
    assert "::warning::" not in step["run"]


def test_init_is_idempotent(tmp_path: Path) -> None:
    (tmp_path / "src" / "solo").mkdir(parents=True)
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "solo"\n', encoding="utf-8"
    )
    init(tmp_path, pin="9.9.9", force=False)
    before = (tmp_path / "pyproject.toml").read_text(encoding="utf-8")
    init(tmp_path, pin="9.9.9", force=False)
    assert (tmp_path / "pyproject.toml").read_text(encoding="utf-8") == before


def test_init_keeps_existing_towncrier_configuration(tmp_path: Path) -> None:
    (tmp_path / "src" / "solo").mkdir(parents=True)
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "solo"\n\n[tool.towncrier]\ndirectory = "changes"\n',
        encoding="utf-8",
    )
    init(tmp_path, pin="9.9.9", force=False)
    text = (tmp_path / "pyproject.toml").read_text(encoding="utf-8")
    assert text.count("[tool.towncrier]") == 1
    assert 'directory = "changes"' in text


def test_publish_workflow_has_no_custom_build_job_by_default(config: Config) -> None:
    document = yaml.safe_load(render("publish.yml", config))
    assert list(document["jobs"]) == [
        "prepare",
        "build",
        "collect",
        "publish",
        "tag-and-release",
    ]
    assert document["jobs"]["collect"]["needs"] == ["prepare", "build"]
    assert document["jobs"]["build"]["if"].strip() == (
        "needs.prepare.outputs.skipped != 'true'"
    )


def test_a_custom_build_replaces_the_build_job_for_its_packages(
    config: Config, repo: Path
) -> None:
    write_custom_build(repo)
    jobs = yaml.safe_load(render("publish.yml", load_config(repo)))["jobs"]
    custom = jobs["custom-build-build_wheels"]
    assert custom["uses"] == "./.github/workflows/build_wheels.yml"
    # Selected for exactly the configured packages, and excluded from the
    # built-in build job for the same ones.
    assert "contains(fromJson('[\"mypkg\"]'), inputs.package)" in custom["if"]
    assert "!contains(fromJson('[\"mypkg\"]'), inputs.package)" in jobs["build"]["if"]


def test_a_custom_build_is_unprivileged_and_gets_no_secrets(
    config: Config, repo: Path
) -> None:
    """It runs repository code, so it must stay on the build side of the gate."""
    write_custom_build(repo)
    custom = yaml.safe_load(render("publish.yml", load_config(repo)))["jobs"][
        "custom-build-build_wheels"
    ]
    assert custom["permissions"] == {"contents": "read"}
    assert "secrets" not in custom


def test_a_custom_build_is_told_the_version_tag_and_artifact_prefix(
    config: Config, repo: Path
) -> None:
    write_custom_build(repo)
    inputs = yaml.safe_load(render("publish.yml", load_config(repo)))["jobs"][
        "custom-build-build_wheels"
    ]["with"]
    assert inputs["version"] == "${{ needs.prepare.outputs.version }}"
    assert inputs["tag"] == "${{ needs.prepare.outputs.tag }}"
    assert inputs["build-dir"] == "${{ needs.prepare.outputs.build_dir }}"
    # The prefix ends in the separator the collect pattern matches on, so a
    # package cannot pick up the artifacts of a sibling it is a prefix of.
    assert inputs["artifact-prefix"] == "dist-${{ inputs.package }}--"


def test_collect_waits_for_every_build_path(config: Config, repo: Path) -> None:
    """A failed matrix leg fails its workflow, which must stop the release."""
    write_custom_build(repo)
    jobs = yaml.safe_load(render("publish.yml", load_config(repo)))["jobs"]
    assert jobs["collect"]["needs"] == [
        "prepare",
        "build",
        "custom-build-build_wheels",
    ]
    # Tolerates the build path that was skipped, never one that failed.
    condition = jobs["collect"]["if"]
    assert "!cancelled()" in condition
    assert "!failure()" in condition


def test_collect_gathers_every_artifact_of_the_package(
    config: Config, repo: Path
) -> None:
    write_custom_build(repo)
    step = next(
        step
        for step in _job_steps(load_config(repo), "collect")
        if str(step.get("uses", "")).startswith("actions/download-artifact")
    )
    assert step["with"]["pattern"] == "dist-${{ inputs.package }}--*"
    assert step["with"]["merge-multiple"] is True


def test_the_gate_covers_what_the_custom_build_produced(
    config: Config, repo: Path
) -> None:
    """The approval is over verified artifacts however they were built."""
    write_custom_build(repo)
    jobs = yaml.safe_load(render("publish.yml", load_config(repo)))["jobs"]
    assert jobs["publish"]["needs"] == ["prepare", "collect"]
    assert jobs["publish"]["environment"]["name"] == "pypi"
    names = [step.get("name", "") for step in jobs["collect"]["steps"]]
    assert "Verify built artifact names and versions" in names


def test_custom_built_packages_still_pass_the_dev_pin_gate(
    config: Config, repo: Path
) -> None:
    """They skip the build job, where the gate normally runs."""
    write_custom_build(repo)
    reloaded = load_config(repo)
    step = next(
        step
        for step in _job_steps(reloaded, "prepare")
        if step.get("name") == "Reject development-release dependency pins"
    )
    assert "contains(fromJson('[\"mypkg\"]'), inputs.package)" in step["if"]
    # Unconfigured repositories keep the gate in the build job alone.
    assert not [
        step
        for step in _job_steps(config, "prepare")
        if step.get("name") == "Reject development-release dependency pins"
    ]


def test_sync_rejects_a_missing_custom_build_workflow(
    config: Config, repo: Path
) -> None:
    write_custom_build(repo, workflow=False)
    with pytest.raises(ReleaseError, match="does not exist"):
        sync(load_config(repo))


def test_sync_rejects_a_custom_build_workflow_that_cannot_be_called(
    config: Config, repo: Path
) -> None:
    write_custom_build(repo)
    target = repo / WORKFLOW_DIR / "build_wheels.yml"
    target.write_text("name: Build wheels\non:\n  push:\n", encoding="utf-8")
    with pytest.raises(ReleaseError, match="no `workflow_call` trigger"):
        sync(load_config(repo))


def test_sync_rejects_a_custom_build_naming_a_generated_workflow(
    config: Config, repo: Path
) -> None:
    """Pointing it at publish.yml would make the workflow call itself."""
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            "\n[tool.towncrier]",
            "\n[[tool.reflex-release.custom-build]]\n"
            'packages = ["mypkg"]\nworkflow = "publish.yml"\n\n[tool.towncrier]',
        ),
        encoding="utf-8",
    )
    with pytest.raises(ReleaseError, match="reflex-release generates"):
        sync(load_config(repo))


def test_sync_round_trips_with_a_custom_build(config: Config, repo: Path) -> None:
    write_custom_build(repo)
    reloaded = load_config(repo)
    sync(reloaded)
    sync(reloaded, check=True)


@pytest.mark.parametrize("mode", ["checkboxes", "text"])
def test_custom_build_workflows_are_valid_yaml(
    config: Config, repo: Path, mode: str
) -> None:
    write_custom_build(repo, extra='expect-artifacts = ["*.whl"]\n')
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            "[tool.reflex-release]",
            f'[tool.reflex-release]\ndispatch-package-inputs = "{mode}"',
        ),
        encoding="utf-8",
    )
    reloaded = load_config(repo)
    for name in managed_workflows(reloaded):
        assert yaml.safe_load(render(name, reloaded))["jobs"], name


WORKFLOW_WITH_DISPATCH = """\
on:
  # a manual trigger with inputs of its own
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
  workflow_call:
    inputs:
      package: { required: true, type: string }
      version:
        required: true
        type: string
      tag:
        required: true
        type: string
      build-dir:
        required: true
        type: string
      artifact-prefix:
        required: true
        type: string
    secrets:
      token:
        required: false
jobs: {}
"""


def test_workflow_call_inputs_reads_the_right_block() -> None:
    """A workflow_dispatch trigger has an `inputs:` block too."""
    assert workflow_call_inputs(WORKFLOW_WITH_DISPATCH) == set(CUSTOM_BUILD_INPUTS)
    assert workflow_call_inputs("on:\n  push:\njobs: {}\n") == set()


def test_the_documented_contract_declares_every_passed_input() -> None:
    """The error message tells people what to write, so it has to be right."""
    assert workflow_call_inputs(CUSTOM_BUILD_CONTRACT) == set(CUSTOM_BUILD_INPUTS)


def test_every_passed_input_is_in_the_contract(config: Config, repo: Path) -> None:
    """The generated call and the contract it is validated against must agree."""
    write_custom_build(repo)
    passed = yaml.safe_load(render("publish.yml", load_config(repo)))["jobs"][
        "custom-build-build_wheels"
    ]["with"]
    assert set(passed) == set(CUSTOM_BUILD_INPUTS)


def test_sync_rejects_a_custom_build_workflow_missing_an_input(
    config: Config, repo: Path
) -> None:
    """GitHub would reject the generated call; catch it in the pull request."""
    write_custom_build(repo)
    target = repo / WORKFLOW_DIR / "build_wheels.yml"
    target.write_text(
        target.read_text(encoding="utf-8").replace(
            '      tag:\n        description: "Tag the checkout with this so the'
            ' build derives that version"\n        required: true\n        type:'
            " string\n",
            "",
        ),
        encoding="utf-8",
    )
    with pytest.raises(ReleaseError, match="does not declare the input"):
        sync(load_config(repo))


def test_collect_keeps_the_git_context_the_hook_used_to_get(config: Config) -> None:
    """post_build.sh moved here from build, whose checkout has history and tags."""
    checkout = _job_steps(config, "collect")[0]
    assert checkout["with"]["fetch-tags"] is True
    assert checkout["with"]["fetch-depth"] == 0


def test_publish_workflow_omits_the_post_release_step_by_default(
    config: Config,
) -> None:
    """A repository that dispatches nothing gets no dispatch step, or its grant."""
    job = yaml.safe_load(render("publish.yml", config))["jobs"]["tag-and-release"]
    assert [step["name"] for step in job["steps"]][-1] == "Create GitHub release"
    assert job["permissions"] == {"contents": "write", "actions": "read"}


def test_publish_workflow_dispatches_the_post_release_workflow(repo: Path) -> None:
    reloaded = set_post_release_workflow(repo, "docs_publish.yml")
    job = yaml.safe_load(render("publish.yml", reloaded))["jobs"]["tag-and-release"]
    step = job["steps"][-1]
    assert step["name"] == "Trigger the post-release workflow"
    assert step["run"].endswith("post-release")
    # The tag comes from the job that computed it, which tag-and-release needs.
    assert step["env"]["TAG"] == "${{ needs.prepare.outputs.tag }}"
    assert step["env"]["VERSION"] == "${{ needs.prepare.outputs.version }}"
    assert set(job["needs"]) >= {"prepare"}
    # Dispatching a workflow needs a write on the actions scope, in the called
    # workflow and in every caller that bounds its permissions.
    assert job["permissions"]["actions"] == "write"
    for name in ("release_from_changelog.yml", "auto_release_internal.yml"):
        rendered = yaml.safe_load(render(name, reloaded))
        assert all(
            job["permissions"]["actions"] == "write"
            for job in rendered["jobs"].values()
            if "actions" in job.get("permissions", {})
        )


@pytest.mark.parametrize(
    "workflow",
    [
        # A workflow this repository gets, by file name...
        "release_from_changelog.yml",
        # ...and by the display name gh resolves it from just as well.
        "Release from changelog",
        # One it would only get if it declared internal packages: sync deletes
        # the file when it does not, so naming it leaves no receiver at all.
        "auto_release_internal.yml",
        "Auto-release internal packages",
    ],
)
def test_sync_rejects_a_generated_post_release_workflow(
    config: Config, repo: Path, workflow: str
) -> None:
    """Handing a published tag back to the release pipeline is not a hook."""
    assert INTERNAL_WORKFLOW not in managed_workflows(config)
    reloaded = set_post_release_workflow(repo, workflow)
    with pytest.raises(ReleaseError, match="names a workflow this tool generates"):
        sync(reloaded)


def test_generated_workflow_names_cover_file_and_display_names() -> None:
    names = generated_workflow_names()
    assert set(GENERATED_WORKFLOWS) <= names
    assert {"Publish to PyPI", "Dispatch release"} <= names


def test_post_release_step_names_the_dispatch_contract(repo: Path) -> None:
    """The generated comment and the dispatch payload come from one list."""
    reloaded = set_post_release_workflow(repo, "docs_publish.yml")
    assert f"# {', '.join(POST_RELEASE_INPUTS)}." in render("publish.yml", reloaded)


def test_a_custom_build_and_a_post_release_workflow_coexist(
    config: Config, repo: Path
) -> None:
    """Both features add optional blocks to the same generated workflow."""
    write_custom_build(repo)
    reloaded = set_post_release_workflow(repo, "docs_publish.yml")
    jobs = yaml.safe_load(render("publish.yml", reloaded))["jobs"]
    assert "custom-build-build_wheels" in jobs
    # The dispatch reads the release facts from prepare, the job that computed
    # them — build no longer carries them, and is skipped for this package.
    step = jobs["tag-and-release"]["steps"][-1]
    assert step["name"] == "Trigger the post-release workflow"
    assert step["env"]["TAG"] == "${{ needs.prepare.outputs.tag }}"
    assert "prepare" in jobs["tag-and-release"]["needs"]


def test_the_gate_survives_the_build_path_that_is_always_skipped(
    config: Config, repo: Path
) -> None:
    """A skipped ancestor must not skip the upload.

    GitHub's implicit success() — the one a job gets when its ``if`` names no
    status function — is evaluated over the transitive dependency closure, so
    the build path that never runs would otherwise skip the upload straight
    through the ``collect`` that was written to absorb it.
    """
    write_custom_build(repo)
    jobs = yaml.safe_load(render("publish.yml", load_config(repo)))["jobs"]
    condition = jobs["publish"]["if"]
    assert "needs.collect.result == 'success'" in condition
    assert "!cancelled()" in condition
    assert "needs.prepare.outputs.skipped != 'true'" in condition


def test_the_tag_is_pushed_only_after_a_successful_upload(
    config: Config, repo: Path
) -> None:
    """`!failure()` would not do: a skipped publish is neither failed nor cancelled."""
    write_custom_build(repo)
    condition = yaml.safe_load(render("publish.yml", load_config(repo)))["jobs"][
        "tag-and-release"
    ]["if"]
    assert "needs.publish.result == 'success'" in condition
    assert "!cancelled()" in condition
    assert "!failure()" not in condition


# The report step is a bash script pinned to `shell: bash` on ubuntu-latest, so
# running it needs a POSIX bash. On Windows `bash` on PATH is the WSL launcher,
# which exits non-zero when no distribution is installed; Git for Windows ships
# a real one next to the git the runners already have.
_GIT_BASH = Path(os.environ.get("PROGRAMFILES", "C:/Program Files"), "Git/bin/bash.exe")
BASH = (
    (str(_GIT_BASH) if _GIT_BASH.is_file() else None)
    if sys.platform == "win32"
    else shutil.which("bash")
)


def _report_script(config: Config) -> str:
    """Return the shell of the release-batch report step.

    Args:
        config: The repository configuration.

    Returns:
        The step's ``run`` script.
    """
    document = yaml.safe_load(render("release_from_changelog.yml", config))
    return document["jobs"]["report"]["steps"][0]["run"]


@pytest.mark.parametrize(
    ("detect", "publish", "publish_last", "any_", "any_last", "expected"),
    [
        # Nothing to release: every leg is legitimately skipped.
        ("success", "skipped", "skipped", "false", "false", 0),
        ("success", "success", "skipped", "true", "false", 0),
        ("success", "success", "success", "true", "true", 0),
        # Detect found packages, yet the leg that publishes them never ran.
        ("success", "skipped", "skipped", "true", "false", 1),
        # A lockstep package held back is a partial release, not a no-op.
        ("success", "success", "skipped", "true", "true", 1),
        ("success", "failure", "skipped", "true", "false", 1),
        ("failure", "skipped", "skipped", "", "", 1),
        ("success", "cancelled", "skipped", "true", "false", 1),
    ],
)
@pytest.mark.skipif(BASH is None, reason="no POSIX bash to run the step with")
def test_the_report_is_red_when_a_leg_with_work_did_not_publish(
    config: Config,
    detect: str,
    publish: str,
    publish_last: str,
    any_: str,
    any_last: str,
    expected: int,
) -> None:
    """A skipped leg is only healthy when detect found nothing for it to do."""
    assert BASH is not None
    result = subprocess.run(
        [BASH, "-c", _report_script(config)],
        env={
            **os.environ,
            "DETECT": detect,
            "PUBLISH": publish,
            "PUBLISH_LAST": publish_last,
            "ANY": any_,
            "ANY_LAST": any_last,
        },
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == expected, result.stdout + result.stderr
