"""Tests for reflex_release.scaffold."""

from __future__ import annotations

import re
from pathlib import Path

import pytest
from reflex_release.actions import ReleaseError
from reflex_release.config import Config, load_config
from reflex_release.scaffold import (
    CORE_WORKFLOWS,
    INTERNAL_WORKFLOW,
    WORKFLOW_DIR,
    default_cli_command,
    init,
    managed_workflows,
    render,
    sync,
    towncrier_config_toml,
)
from reflex_release.versions import ACTIONS


def test_render_substitutes_every_placeholder(config: Config) -> None:
    for name in CORE_WORKFLOWS:
        rendered = render(name, config)
        assert not re.search(r"@@[A-Z_]+@@", rendered)
        assert "Generated by reflex-release" in rendered


def test_render_uses_the_configured_branches(config: Config, repo: Path) -> None:
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text().replace(
            'packages-dir = "packages"',
            'packages-dir = "packages"\nmain-branch = "trunk"\nprerelease-branch-prefix = "pre/"',
        )
    )
    rendered = render("release_from_changelog.yml", load_config(repo))
    assert 'branches: ["trunk", "pre/**", "r/hotfix/**"]' in rendered


def test_render_lists_every_release_action(config: Config) -> None:
    rendered = render("dispatch_release.yml", config)
    for action in ACTIONS:
        assert f"          - {action}\n" in rendered


def test_render_uses_the_pinned_cli_command(config: Config, repo: Path) -> None:
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text().replace(
            "[tool.reflex-release]",
            '[tool.reflex-release]\ncli-command = "uvx reflex-release@1.2.3"',
        )
    )
    assert "uvx reflex-release@1.2.3 detect" in render(
        "release_from_changelog.yml", load_config(repo)
    )


def test_internal_workflow_is_only_generated_when_configured(
    config: Config, repo: Path
) -> None:
    assert managed_workflows(config) == CORE_WORKFLOWS
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text().replace(
            'packages-dir = "packages"',
            'packages-dir = "packages"\ninternal-packages = ["widget-core"]',
        )
    )
    reloaded = load_config(repo)
    assert managed_workflows(reloaded) == (*CORE_WORKFLOWS, INTERNAL_WORKFLOW)
    assert '- "packages/widget-core/**"' in render(INTERNAL_WORKFLOW, reloaded)


def test_sync_writes_then_verifies(config: Config, repo: Path) -> None:
    sync(config)
    for name in CORE_WORKFLOWS:
        assert (repo / WORKFLOW_DIR / name).is_file()
    sync(config, check=True)


def test_sync_check_detects_drift(config: Config, repo: Path) -> None:
    sync(config)
    target = repo / WORKFLOW_DIR / "publish.yml"
    target.write_text(
        target.read_text().replace("Publish to PyPI", "Publish somewhere")
    )
    with pytest.raises(ReleaseError, match="out of date"):
        sync(config, check=True)


def test_sync_refuses_to_clobber_a_foreign_workflow(config: Config, repo: Path) -> None:
    target = repo / WORKFLOW_DIR / "publish.yml"
    target.parent.mkdir(parents=True)
    target.write_text("name: something else\n")
    with pytest.raises(ReleaseError, match="not generated by reflex-release"):
        sync(config)
    sync(config, force=True)
    assert "Generated by reflex-release" in target.read_text()


@pytest.mark.parametrize(
    ("pin", "expected"),
    [("1.2.3", "uvx reflex-release@1.2.3"), ("", "uvx reflex-release")],
)
def test_default_cli_command(pin: str, expected: str) -> None:
    assert default_cli_command(pin) == expected


def test_towncrier_config_uses_the_github_remote(repo: Path) -> None:
    from .conftest import git

    git(repo, "remote", "add", "origin", "https://github.com/acme/widgets.git")
    assert "https://github.com/acme/widgets/issues/{issue}" in towncrier_config_toml(
        repo
    )


def test_towncrier_config_falls_back_without_a_remote(repo: Path) -> None:
    assert "OWNER/REPO" in towncrier_config_toml(repo)


def test_init_sets_up_a_bare_repository(tmp_path: Path) -> None:
    (tmp_path / "src" / "solo").mkdir(parents=True)
    (tmp_path / "pyproject.toml").write_text('[project]\nname = "solo"\n')
    init(tmp_path, pin="9.9.9", force=False)

    config = load_config(tmp_path)
    assert config.root_package == "solo"
    assert config.cli_command == "uvx reflex-release@9.9.9"
    assert (tmp_path / "news" / ".gitkeep").is_file()
    for name in CORE_WORKFLOWS:
        assert (tmp_path / WORKFLOW_DIR / name).is_file()
    sync(config, check=True)


def test_init_is_idempotent(tmp_path: Path) -> None:
    (tmp_path / "src" / "solo").mkdir(parents=True)
    (tmp_path / "pyproject.toml").write_text('[project]\nname = "solo"\n')
    init(tmp_path, pin="9.9.9", force=False)
    before = (tmp_path / "pyproject.toml").read_text()
    init(tmp_path, pin="9.9.9", force=False)
    assert (tmp_path / "pyproject.toml").read_text() == before


def test_init_keeps_existing_towncrier_configuration(tmp_path: Path) -> None:
    (tmp_path / "src" / "solo").mkdir(parents=True)
    (tmp_path / "pyproject.toml").write_text(
        '[project]\nname = "solo"\n\n[tool.towncrier]\ndirectory = "changes"\n'
    )
    init(tmp_path, pin="9.9.9", force=False)
    text = (tmp_path / "pyproject.toml").read_text()
    assert text.count("[tool.towncrier]") == 1
    assert 'directory = "changes"' in text
