name: docs whitelist check

on:
  pull_request:
    paths:
      - 'docs/app/reflex_docs/whitelist.py'
      - '.github/workflows/docs_whitelist.yml'

permissions:
  contents: read

jobs:
  check-whitelist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Assert whitelist is empty
        run: echo -e "\nassert not WHITELISTED_PAGES, f'WHITELISTED_PAGES includes {WHITELISTED_PAGES}'" | cat "docs/app/reflex_docs/whitelist.py" - | python3
