name: pre-commit
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.id }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["main"]
  push:
    # Note even though this job is called "pre-commit" and runs "pre-commit", this job will run
    # also POST-commit on main also!  In case there are mishandled merge conflicts / bad auto-resolves
    # when merging into main branch.
    branches: ["main"]

jobs:
  pre-commit:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-tags: true
          fetch-depth: 0
      - uses: ./.github/actions/setup_build_env
        with:
          python-version: 3.14
          run-uv-sync: true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          clean: false
          fetch-tags: true
          fetch-depth: 0
      - run: uv run pre-commit run --all-files --show-diff-on-failure
